In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import pandas as pd

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [4]:
iris=load_iris()

In [5]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower']=iris.target
df['flower_name']=df.flower.apply(lambda x: iris.target_names[x])
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower,flower_name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

In [18]:
model_params={
    'svm':{
        'model':SVC(C=10),
        'params':{
            'kernel':['rbf','linear'],
            'gamma':['scale', 'auto']
        }
        
    },
    'LogisticRegression':{
        'model':LogisticRegression(max_iter=1000),
        'params':{
            'solver':['newton-cg', 'lbfgs', 'liblinear'] 
        }
    },
    'DecisionTreeClassifier':{
        'model':DecisionTreeClassifier(),
        'params':{
            'criterion':['gini','entropy']
        }
        
    },
    'RandomForestClassifier':{
        'model':RandomForestClassifier(),
        'params':{
            'criterion':['gini','entropy'],
            'max_features':["log2"]
        } 
    } 
}

In [19]:
score=[]
for name,model in model_params.items():
    clf=GridSearchCV(model['model'],model['params'],cv=10,return_train_score=False)
    clf.fit(iris.data,iris.target)
    score.append({
        'model':name,
        'best_score':clf.best_score_,
        'best_params': clf.best_params_
    })

In [20]:
pd.DataFrame(score)

,model,best_score,best_params
0,svm,0.980000,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}"
1,LogisticRegression,0.973333,{'solver': 'newton-cg'}
2,DecisionTreeClassifier,0.960000,{'criterion': 'gini'}
3,RandomForestClassifier,0.966667,"{'criterion': 'gini', 'max_features': 'log2'}"